tasks:
  - name: Install dependencies
    init: pip install pytest pytest-benchmark pytest-subtests pytest-cov
  - name: Clear screen
    init: clear
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - littlefoxteam.vscode-python-test-adapter