tasks:
  - name: Install dependencies
    init: pip install pytest pytest-benchmark pytest-subtests pytest-cov
  - name: Clear screen
    init: clear
  - name: branding
    init: >
      echo    _____       _________      _            __  __
  / ___/__  __/ __/ __(_)____(_)__  ____  / /_/ /_  __
  \__ \/ / / / /_/ /_/ / ___/ / _ \/ __ \/ __/ / / / /
 ___/ / /_/ / __/ __/ / /__/ /  __/ / / / /_/ / /_/ /
/____/\__,_/_/ /_/ /_/\___/_/\___/_/ /_/\__/_/\__, /  
  / ___/____ ___  ____ ______/ /_            /____/   
  \__ \/ __ `__ \/ __ `/ ___/ __/                     
 ___/ / / / / / / /_/ / /  / /_                       
/____/_/ /_/ /_/\__,_/_/   \__/                       
  ______           _       _                          
 /_  __/________ _(_)___  (_)___  ____ _              
  / / / ___/ __ `/ / __ \/ / __ \/ __ `/              
 / / / /  / /_/ / / / / / / / / / /_/ /               
/_/ /_/   \__,_/_/_/ /_/_/_/ /_/\__, /                
                               /____/